/**
 * Shared TypeScript types for the IAI Agent System.
 *
 * These interfaces mirror the Supabase table schemas:
 *   agent_health_events, agent_alerts, agent_test_runs,
 *   agent_pm_reports, agent_proposals, agent_logs
 */

import type { SLOKey, SLOTier } from './slo-definitions';

// ── Enums & Literals ─────────────────────────────────────────────────

export type AgentName =
  | 'health-monitor'
  | 'tester-agent'
  | 'pm-agent'
  | 'cs-agent';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'fatal';

export type AlertSeverity = 'critical' | 'high' | 'medium' | 'low';

export type CheckStatus = 'pass' | 'fail' | 'degraded' | 'error';

export type TestStatus = 'pass' | 'fail' | 'skip' | 'error';

export type ProposalStatus = 'proposed' | 'approved' | 'rejected' | 'implemented';

// ── agent_health_events ──────────────────────────────────────────────

/** A single health check result written by the health-monitor agent. */
export interface CheckResult {
  id?: string;
  /** ISO 8601 timestamp */
  created_at?: string;
  /** Which agent ran this check */
  agent: AgentName;
  /** Human-readable check name, e.g. "edge_function_latency" */
  check_name: string;
  /** Which SLO this check maps to (if any) */
  slo_key?: SLOKey;
  /** pass / fail / degraded / error */
  status: CheckStatus;
  /** The measured value */
  measured_value: number | null;
  /** Unit of measured_value */
  unit?: string;
  /** SLO target for context */
  target_value?: number | null;
  /** Human-readable summary */
  message: string;
  /** Arbitrary structured metadata */
  metadata?: Record<string, unknown>;
  /** How long the check took to run, in ms */
  duration_ms?: number;
  /** Session grouping ID */
  session_id?: string;
}

// ── agent_alerts ─────────────────────────────────────────────────────

/** An alert fired by any agent when an SLO is breached or anomaly detected. */
export interface AlertPayload {
  id?: string;
  created_at?: string;
  /** Which agent fired the alert */
  agent: AgentName;
  /** critical / high / medium / low */
  severity: AlertSeverity;
  /** Related SLO key */
  slo_key?: SLOKey;
  /** Short title for the alert */
  title: string;
  /** Detailed description */
  message: string;
  /** Measured value that triggered the alert */
  measured_value?: number | null;
  /** The threshold that was breached */
  threshold_value?: number | null;
  /** Was an email notification sent? */
  email_sent?: boolean;
  /** Has a human acknowledged this alert? */
  acknowledged?: boolean;
  /** Deduplication key (same key = same alert, won't re-fire within window) */
  dedup_key?: string;
  /** Extra context */
  metadata?: Record<string, unknown>;
}

// ── agent_test_runs ──────────────────────────────────────────────────

/** A single test result from the tester-agent. */
export interface TestRunResult {
  id?: string;
  created_at?: string;
  agent: AgentName;
  /** Test suite name, e.g. "auth-flow", "stripe-webhook" */
  suite: string;
  /** Individual test name */
  test_name: string;
  /** pass / fail / skip / error */
  status: TestStatus;
  /** How long the test took, in ms */
  duration_ms?: number;
  /** Error message if status is fail/error */
  error_message?: string;
  /** Stack trace or debug info */
  error_details?: string;
  /** Structured test metadata (request/response, screenshots, etc.) */
  metadata?: Record<string, unknown>;
  /** Session grouping ID */
  session_id?: string;
}

// ── agent_pm_reports ─────────────────────────────────────────────────

/** A periodic report generated by the PM agent. */
export interface PMReport {
  id?: string;
  created_at?: string;
  agent: AgentName;
  /** Report type: daily, weekly, incident, ad-hoc */
  report_type: 'daily' | 'weekly' | 'incident' | 'ad-hoc';
  /** Report title */
  title: string;
  /** Full report body (markdown) */
  body: string;
  /** Summary / TL;DR */
  summary?: string;
  /** Time period covered: { from: ISO, to: ISO } */
  period?: { from: string; to: string };
  /** SLO compliance snapshot */
  slo_snapshot?: Record<SLOKey, { status: CheckStatus; measured: number | null }>;
  /** Was the report emailed? */
  email_sent?: boolean;
  /** Extra metadata */
  metadata?: Record<string, unknown>;
}

// ── agent_proposals ──────────────────────────────────────────────────

/** A product/engineering proposal generated by the PM agent. */
export interface Proposal {
  id?: string;
  created_at?: string;
  agent: AgentName;
  /** Short title */
  title: string;
  /** What the proposal recommends */
  description: string;
  /** Why this matters — data-backed rationale */
  rationale: string;
  /** Which SLO(s) this proposal would improve */
  related_slos?: SLOKey[];
  /** Estimated effort: small / medium / large */
  estimated_effort?: 'small' | 'medium' | 'large';
  /** Priority: p0 / p1 / p2 / p3 */
  priority?: 'p0' | 'p1' | 'p2' | 'p3';
  /** Current status */
  status: ProposalStatus;
  /** Human review notes */
  review_notes?: string;
  /** Extra metadata */
  metadata?: Record<string, unknown>;
}

// ── agent_logs ───────────────────────────────────────────────────────

/** A structured log entry written to the agent_logs table. */
export interface LogEntry {
  id?: string;
  created_at?: string;
  agent: AgentName;
  level: LogLevel;
  message: string;
  /** Arbitrary structured data */
  metadata?: Record<string, unknown>;
  /** How long the operation took, in ms */
  duration_ms?: number;
  /** Session grouping ID */
  session_id?: string;
}

// ── Utility types ────────────────────────────────────────────────────

/** Options passed when initializing an agent run. */
export interface AgentRunOptions {
  agent: AgentName;
  sessionId?: string;
  dryRun?: boolean;
}

/** Standard response shape from agent operations. */
export interface AgentResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  duration_ms?: number;
}
