/**
 * learningContent.js — All 20 lessons for the Learn section
 *
 * 4 Modules × 5 Lessons each = 20 total lessons
 * Each lesson has:
 *   - audioScript: array of lines for TTS (same format as PrepRadio)
 *     '...' = 2-second pause
 *   - keyTakeaways: 3 bullet points shown on completion
 *   - quiz: 3 active recall questions (MCQ, T/F, recall, or apply)
 *
 * Audio scripts follow PrepRadio conventions:
 *   - Short sentences (12-18 words max)
 *   - Liberal commas for natural pauses
 *   - Conversational, coaching tone
 *   - '...' for deliberate pauses between sections
 */

// ============================================================
// MODULE 1: INTERVIEW FUNDAMENTALS
// ============================================================

const module1 = {
  id: 1,
  title: 'Interview Fundamentals',
  icon: '\uD83C\uDFAF',
  description: 'How behavioral interviews work and what makes answers great',
  lessons: [
    // ---- LESSON 1-1 ----
    {
      id: '1-1',
      title: 'How Behavioral Interviews Work',
      duration: '4 min',
      audioScript: [
        "Welcome to your first lesson.",
        "Today, we're going to demystify behavioral interviews.",
        "By the end, you'll understand exactly what interviewers are looking for.",
        '...',
        "Here's the core idea behind behavioral interviewing.",
        "Past behavior is the single best predictor of future behavior.",
        "That's not just an opinion, it's backed by decades of research.",
        "Industrial psychologists discovered that asking about real experiences, produces far more accurate hiring decisions, than hypothetical questions.",
        '...',
        "So when an interviewer says, tell me about a time, they're not making conversation.",
        "They're using a scientifically validated technique.",
        "They want to hear what you actually did, in a real situation.",
        "Not what you think you would do, in an imaginary one.",
        '...',
        "Here's why this matters for you.",
        "A vague answer like, I'm a team player, tells the interviewer nothing.",
        "But a specific story, about a time you resolved a conflict between two coworkers, by mediating a meeting and creating a shared action plan?",
        "That tells them everything.",
        '...',
        "The pattern you'll see again and again is, tell me about a time when.",
        "Tell me about a time you handled a difficult situation.",
        "Tell me about a time you showed leadership.",
        "Tell me about a time you failed.",
        "Each of these is an invitation, to share a real story from your experience.",
        '...',
        "And here's the good news.",
        "You don't need dozens of stories.",
        "Most successful candidates prepare seven to ten strong stories, and adapt them across many different questions.",
        "One great story about leading a team through a crisis, can answer questions about leadership, pressure, decision-making, and teamwork.",
        '...',
        "In the next lesson, we'll teach you the exact framework for structuring these stories.",
        "It's called the STAR method, and it will become your best friend.",
        "For now, remember this, real stories beat hypothetical answers, every single time.",
      ],
      keyTakeaways: [
        'Past behavior is the best predictor of future behavior \u2014 that\'s why interviewers ask "tell me about a time"',
        'Specific real stories beat vague or hypothetical answers every time',
        '7-10 strong stories can cover dozens of different interview questions',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What is the core principle behind behavioral interviews?',
          options: [
            'Testing how creative you are under pressure',
            'Past behavior predicts future behavior',
            'Seeing if you can think on your feet',
            'Checking your knowledge of the company',
          ],
          correctIndex: 1,
          explanation: 'Behavioral interviewing is built on the research-backed principle that past behavior is the strongest predictor of future performance.',
        },
        {
          type: 'tf',
          question: 'Hypothetical answers ("I would...") score just as well as real experience stories ("I did...").',
          correctAnswer: false,
          explanation: 'Real experience stories are far more convincing. Interviewers are specifically trained to probe for actual past behavior, not hypothetical responses.',
        },
        {
          type: 'recall',
          question: 'How many core stories do most successful candidates prepare?',
          expectedAnswer: '7 to 10 stories',
          explanation: 'The recommended range is 7-10 core career stories. Each story can be adapted to answer 3-5 different questions, covering 35-50 questions total.',
        },
      ],
    },

    // ---- LESSON 1-2 ----
    {
      id: '1-2',
      title: 'The Anatomy of a Great STAR Answer',
      duration: '4 min',
      audioScript: [
        "In this lesson, you'll learn the STAR method.",
        "This is the single most important framework in interview preparation.",
        "Once you internalize it, every answer you give will be clearer, more compelling, and more memorable.",
        '...',
        "STAR stands for Situation, Task, Action, and Result.",
        "Let's break down each part.",
        '...',
        "Situation is where you set the scene.",
        "When and where did this happen? What was the context?",
        "Keep it brief, just two to three sentences.",
        "Think of it as the opening shot of a movie.",
        "Your goal is to give the interviewer just enough context to follow your story.",
        '...',
        "Task is where you define your role.",
        "What were you specifically responsible for?",
        "What was at stake?",
        "This is where you establish ownership.",
        "Use the word I, not we.",
        "Again, keep it concise, two to three sentences.",
        '...',
        "Action is the heart of your answer.",
        "This should be the longest section, roughly sixty percent of your total answer.",
        "What specific steps did you take?",
        "Don't list vague responsibilities.",
        "Zoom in on two to three concrete actions.",
        "Instead of saying, I coordinated with the team, say, I scheduled three meetings with department heads, created a shared timeline, and personally followed up with each stakeholder.",
        "The more specific your actions, the more credible your answer.",
        '...',
        "Result is your closer.",
        "What happened because of your actions?",
        "Quantify whenever possible, numbers, percentages, time saved, money saved.",
        "If you can't quantify, describe the impact qualitatively.",
        "And always end with what you learned.",
        "The lesson learned shows self-awareness and growth.",
        '...',
        "Here's the time allocation that works best.",
        "Situation, about ten percent of your answer.",
        "Task, about ten percent.",
        "Action, about sixty percent.",
        "Result, about twenty percent.",
        "Most people do the opposite, they spend too long setting up the story and rush through their actions.",
        "Flip that ratio, and your answers will immediately improve.",
      ],
      keyTakeaways: [
        'STAR = Situation (10%), Task (10%), Action (60%), Result (20%)',
        'Action is the hero section \u2014 detail 2-3 specific steps YOU took',
        'Always quantify your Result and include what you learned',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'Which STAR section should take the MOST time in your answer?',
          options: [
            'Situation \u2014 set the context thoroughly',
            'Task \u2014 explain your responsibilities',
            'Action \u2014 detail the specific steps you took',
            'Result \u2014 describe every outcome',
          ],
          correctIndex: 2,
          explanation: 'Action should be roughly 60% of your answer. It\'s where you prove your competency by describing the specific steps YOU took.',
        },
        {
          type: 'recall',
          question: 'What does STAR stand for?',
          expectedAnswer: 'Situation, Task, Action, Result',
          explanation: 'STAR = Situation (set the scene), Task (define your role), Action (detail your steps), Result (show the outcome + lesson learned).',
        },
        {
          type: 'apply',
          question: 'Think of a recent work achievement. Can you identify the Situation, Task, Action, and Result? Take a moment to mentally walk through each section.',
          prompt: 'There\'s no wrong answer here \u2014 this is about building the habit of structuring your experiences in STAR format.',
        },
      ],
    },

    // ---- LESSON 1-3 ----
    {
      id: '1-3',
      title: 'Stories, Not Reports',
      duration: '4 min',
      audioScript: [
        "Here's a mistake almost every candidate makes.",
        "They give reports instead of stories.",
        "In this lesson, you'll learn the difference, and it will transform your answers.",
        '...',
        "A report sounds like this.",
        "In my role as a project manager, I was responsible for overseeing deliverables, managing timelines, and ensuring stakeholder alignment.",
        "That's a job description, not a story.",
        "It tells the interviewer what you were supposed to do, but not what you actually did.",
        '...',
        "A story sounds like this.",
        "Last March, our biggest client threatened to pull their contract after two missed deadlines.",
        "I personally called the client, acknowledged the problem, and proposed a recovery plan with weekly check-ins.",
        "Within six weeks, we were back on track, and they renewed for another year.",
        "See the difference?",
        '...',
        "Reports are general. Stories are specific.",
        "Reports say, I handled many situations like this. Stories say, here's exactly what happened on March 15th.",
        "Reports use vague verbs like managed, oversaw, facilitated. Stories use vivid verbs like called, built, discovered, confronted.",
        '...',
        "Here are three rules for telling stories instead of reports.",
        '...',
        "Rule one, pick ONE specific moment.",
        "Not a pattern of behavior over months.",
        "One event, one challenge, one resolution.",
        "If you can't name the month it happened, you're probably being too vague.",
        '...',
        "Rule two, include at least one detail that only someone who was there would know.",
        "The name of the client. The exact number. The time of day.",
        "These details signal authenticity.",
        "Interviewers can tell when you're making things up, and details are how they verify.",
        '...',
        "Rule three, make yourself the main character.",
        "Use I, not we.",
        "Even if it was a team effort, focus on YOUR specific contributions.",
        "The interviewer is hiring you, not your team.",
        '...',
        "When you tell stories instead of reports, something magical happens.",
        "The interviewer leans in. They remember you.",
        "Because humans are wired for stories, not bullet points.",
        "In your next practice session, try telling a story instead of giving a report.",
        "You'll feel the difference immediately.",
      ],
      keyTakeaways: [
        'Reports list duties ("I managed..."); Stories show specific moments ("Last March, I called the client and...")',
        'Include one detail only someone who was there would know \u2014 it signals authenticity',
        'Use "I" not "we" \u2014 the interviewer is hiring you, not your team',
      ],
      quiz: [
        {
          type: 'tf',
          question: '"I handled many situations like this throughout my career" is a strong interview answer.',
          correctAnswer: false,
          explanation: 'This is a report, not a story. Strong answers focus on ONE specific moment with concrete details. "Many situations" is vague and unmemorable.',
        },
        {
          type: 'mcq',
          question: 'Which of these demonstrates "telling a story" instead of "giving a report"?',
          options: [
            '"I was responsible for managing client relationships"',
            '"Last March, I called our biggest client after two missed deadlines and proposed a recovery plan"',
            '"I have extensive experience in stakeholder management"',
            '"In my role, I facilitated cross-functional collaboration"',
          ],
          correctIndex: 1,
          explanation: 'Option B is specific (Last March), personal (I called), and detailed (two missed deadlines, recovery plan). The others are generic job descriptions.',
        },
        {
          type: 'apply',
          question: 'Think of ONE specific moment at work you\'re proud of. Not a general responsibility \u2014 one specific day or event. Can you name the month it happened?',
          prompt: 'If you can name the month, you have a story. If you can only describe it generally, dig deeper into one specific instance.',
        },
      ],
    },

    // ---- LESSON 1-4 ----
    {
      id: '1-4',
      title: 'What Interviewers Actually Score',
      duration: '4 min',
      audioScript: [
        "Most candidates have no idea how they're actually being evaluated.",
        "In this lesson, I'll pull back the curtain.",
        "When you understand the scoring rubric, you can give the interviewer exactly what they need.",
        '...',
        "Most structured interviews use something called behavioral anchors.",
        "These are specific observable behaviors that map to a rating scale.",
        "Usually one through five, or one through four.",
        "The interviewer listens to your story and checks which behaviors you demonstrated.",
        '...',
        "Here's what they're typically scoring.",
        '...',
        "First, specificity.",
        "Did you describe a real situation with concrete details?",
        "Or did you speak in generalities?",
        "Specific answers score higher, every time.",
        '...',
        "Second, ownership.",
        "Did you clearly describe YOUR actions?",
        "Or did you hide behind the team?",
        "They want to hear what you personally did, decided, and contributed.",
        '...',
        "Third, impact.",
        "Did your actions lead to a measurable result?",
        "Numbers are gold. Percentages, dollar amounts, time saved.",
        "Even qualitative impact counts, like improved team morale or stronger client relationship.",
        '...',
        "Fourth, reflection.",
        "Did you show awareness of what you learned?",
        "This separates good candidates from great ones.",
        "Anyone can tell a success story.",
        "But candidates who reflect on what they'd do differently, or what they learned, show growth mindset.",
        '...',
        "And fifth, relevance.",
        "Does your example actually answer the question that was asked?",
        "You'd be surprised how many candidates tell a great story, that has nothing to do with the competency being assessed.",
        '...',
        "Here's a secret most people miss.",
        "Your actions matter more than your outcome.",
        "Even if a project failed, if you demonstrated strong judgment, clear communication, and accountability in your actions, you can still score a five out of five.",
        "The interviewer is scoring your behavior, not your results.",
        '...',
        "So when you practice, ask yourself these five questions.",
        "Was I specific? Did I show ownership? Did I demonstrate impact? Did I reflect on what I learned? And was my story relevant to the question?",
        "If you can answer yes to all five, you've given a top-tier response.",
      ],
      keyTakeaways: [
        'Interviewers score 5 things: Specificity, Ownership, Impact, Reflection, and Relevance',
        'Your actions matter more than the outcome \u2014 even failure stories can score 5/5',
        'Always include what you learned \u2014 reflection separates good from great',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What matters MORE to the interviewer when scoring your answer?',
          options: [
            'The final outcome of the project',
            'Your specific actions and behaviors',
            'How long the project took',
            'How many people were involved',
          ],
          correctIndex: 1,
          explanation: 'Interviewers score your behavior, not just your results. Strong actions with a poor outcome can still earn a top score if you demonstrated good judgment and accountability.',
        },
        {
          type: 'recall',
          question: 'Name at least 3 of the 5 things interviewers typically score in behavioral answers.',
          expectedAnswer: 'Specificity, Ownership, Impact, Reflection, Relevance',
          explanation: 'The 5 scoring dimensions: (1) Specificity of details, (2) Personal ownership/actions, (3) Measurable impact, (4) Reflection/learning, (5) Relevance to the question asked.',
        },
        {
          type: 'tf',
          question: 'If a project you led ultimately failed, you should never use it as an interview example.',
          correctAnswer: false,
          explanation: 'Failure stories can score very high if you demonstrate strong actions, accountability, and genuine reflection. Interviewers love candidates who can discuss failures with maturity.',
        },
      ],
    },

    // ---- LESSON 1-5 ----
    {
      id: '1-5',
      title: 'The Confidence Equation',
      duration: '3 min',
      audioScript: [
        "Let's talk about the elephant in the room.",
        "Interview anxiety.",
        "Almost everyone experiences it, and it's completely normal.",
        "But here's the good news, confidence isn't something you're born with. It's something you build.",
        '...',
        "The confidence equation has three parts.",
        "Preparation, plus practice, plus perspective.",
        '...',
        "Preparation means knowing your stories.",
        "When you've identified seven to ten core experiences, and you've structured them using STAR, you eliminate the biggest source of anxiety, not knowing what to say.",
        "You don't need to memorize scripts.",
        "You just need to know your stories well enough to tell them naturally.",
        '...',
        "Practice means saying your answers out loud.",
        "Reading them in your head doesn't count.",
        "Your brain processes spoken language differently than written language.",
        "The more times you've spoken a story out loud, the more natural it will feel in the interview.",
        "This is why this app exists, to give you that practice.",
        '...',
        "Perspective means remembering that the interview is a conversation, not an interrogation.",
        "The interviewer wants you to succeed.",
        "They have an open position, and they're hoping you're the right fit.",
        "You're not being tested, you're being given a chance to share your experience.",
        '...',
        "Here's the eighty-twenty rule of interview prep.",
        "Twenty percent of your preparation produces eighty percent of your results.",
        "That twenty percent is, knowing your stories and practicing them out loud.",
        "Not researching every possible question.",
        "Not memorizing the company's annual report.",
        "Just know your stories, and practice telling them.",
        '...',
        "One more thing about nervousness.",
        "Research shows that reframing anxiety as excitement, actually improves performance.",
        "Instead of telling yourself, I'm so nervous, try saying, I'm excited about this opportunity.",
        "Your body can't tell the difference between anxiety and excitement.",
        "But your brain can, and it responds differently.",
        '...',
        "You've now completed Module One.",
        "You understand how behavioral interviews work, the STAR framework, the power of stories, what interviewers score, and how to build genuine confidence.",
        "In Module Two, we'll dive deep into each STAR component.",
        "You're already ahead of most candidates.",
      ],
      keyTakeaways: [
        'Confidence = Preparation (know your stories) + Practice (say them out loud) + Perspective (it\'s a conversation)',
        'The 80/20 rule: knowing your stories + practicing aloud = 80% of prep value',
        'Reframe anxiety as excitement \u2014 your body responds the same way, but your brain performs better',
      ],
      quiz: [
        {
          type: 'tf',
          question: 'Being nervous always hurts your interview performance.',
          correctAnswer: false,
          explanation: 'Research shows that reframing nervousness as excitement can actually improve performance. Some level of activation helps you perform at your best.',
        },
        {
          type: 'mcq',
          question: 'According to the 80/20 rule of interview prep, what produces the most results?',
          options: [
            'Researching every possible question',
            'Memorizing the company\'s mission statement',
            'Knowing your stories and practicing them out loud',
            'Reading sample answers online',
          ],
          correctIndex: 2,
          explanation: 'The highest-impact prep activity is knowing your 7-10 core stories and practicing them aloud. This covers 80% of what you need.',
        },
        {
          type: 'apply',
          question: 'Rate your current interview confidence from 1-5. After completing all four modules, come back and rate yourself again. Most people improve by at least 2 points.',
          prompt: 'This isn\'t graded \u2014 it\'s a baseline measurement. Honest self-assessment helps you track your growth.',
        },
      ],
    },
  ],
};


// ============================================================
// MODULE 2: STAR DEEP DIVE
// ============================================================

const module2 = {
  id: 2,
  title: 'STAR Deep Dive',
  icon: '\u2B50',
  description: 'Master each STAR component with techniques that make answers shine',
  lessons: [
    // ---- LESSON 2-1 ----
    {
      id: '2-1',
      title: 'Situation: Setting the Scene',
      duration: '4 min',
      audioScript: [
        "Welcome to Module Two.",
        "Over the next five lessons, we'll master each part of the STAR framework.",
        "Let's start with Situation.",
        '...',
        "The Situation section is your opening shot.",
        "Its job is to give the interviewer just enough context to understand your story.",
        "Not too much, not too little.",
        '...',
        "The biggest mistake people make with Situation? Going on too long.",
        "They spend two minutes describing the company, the team structure, the background.",
        "By the time they get to their actual actions, the interviewer has mentally checked out.",
        '...',
        "Here's the two-sentence rule.",
        "Your Situation should be about two sentences long.",
        "Sentence one, when and where. Last year at my previous company, or During my second year as a nurse in the ICU.",
        "Sentence two, the challenge or context. Our largest client was threatening to leave, or We were short-staffed during flu season and admissions doubled.",
        '...',
        "That's it. Two sentences. Maybe three if the context is complex.",
        "Remember, Situation should be about ten percent of your answer.",
        "In a three-minute answer, that's about eighteen seconds.",
        '...',
        "What makes a Situation effective?",
        '...',
        "First, it establishes stakes.",
        "The interviewer should immediately understand why this mattered.",
        "Our biggest client was worth two million in annual revenue, is more compelling than, we had a client issue.",
        '...',
        "Second, it's specific.",
        "In March of 2024, is better than, a while back.",
        "At our downtown hospital with 400 beds, is better than, at my hospital.",
        "Specific details make your story feel real and credible.",
        '...',
        "Third, it sets up YOUR role naturally.",
        "The Situation should make it obvious why you were involved.",
        "As the lead on this project, or As the only experienced nurse on shift that night.",
        '...',
        "Here's a template you can use.",
        "In, time period, at, location or company, bracket the challenge or context, bracket.",
        "As, your role, I was, connection to the situation.",
        "Fill in those blanks, and you have a perfect Situation every time.",
        '...',
        "Practice this with your own stories.",
        "Can you set the scene in two sentences?",
        "If not, you're including too much detail. Save it for the Action section.",
      ],
      keyTakeaways: [
        'Follow the 2-sentence rule: Sentence 1 = when/where, Sentence 2 = the challenge/context',
        'Establish stakes early \u2014 make the interviewer understand why this mattered',
        'Be specific with details (dates, numbers, roles) \u2014 it signals authenticity',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What is the ideal length for the Situation section of a STAR answer?',
          options: [
            'About 1 minute \u2014 give thorough context',
            'About 2-3 sentences \u2014 brief but vivid',
            'As long as needed to explain the background',
            'Just one word to name the topic',
          ],
          correctIndex: 1,
          explanation: 'The 2-sentence rule: Situation should be ~10% of your answer. In a 3-minute response, that\'s roughly 18 seconds or 2-3 sentences.',
        },
        {
          type: 'tf',
          question: 'Including specific details like dates and numbers in your Situation makes it too long.',
          correctAnswer: false,
          explanation: 'Specific details like "In March 2024" or "our $2M client" actually make your Situation MORE concise and MORE credible than vague language like "a while back" or "a big client."',
        },
        {
          type: 'apply',
          question: 'Think of a work challenge you faced. Can you describe the Situation in exactly 2 sentences? One for when/where, one for the challenge.',
          prompt: 'Practice the 2-sentence format: "[Time] at [place], [challenge/context]. As [your role], I [connection]."',
        },
      ],
    },

    // ---- LESSON 2-2 ----
    {
      id: '2-2',
      title: 'Task: Showing Ownership',
      duration: '3 min',
      audioScript: [
        "Now let's talk about Task, the section most people get wrong.",
        "Task is where you define what YOU were responsible for.",
        "Not the team. Not the department. You.",
        '...',
        "The most common mistake?",
        "Saying we instead of I.",
        "Our team needed to fix the problem. We had to improve the process.",
        "That tells the interviewer nothing about YOUR role.",
        '...',
        "Instead, try this.",
        "I was responsible for redesigning the workflow.",
        "My job was to reduce the error rate by fifty percent.",
        "I was tasked with managing the client relationship during the transition.",
        "Hear the difference? Each sentence starts with I and defines a specific responsibility.",
        '...',
        "Task should answer three questions.",
        "What was your specific role?",
        "What was expected of you?",
        "And what was at stake if you didn't deliver?",
        '...',
        "Here's a powerful formula.",
        "I was responsible for, specific deliverable, because, reason or stakes.",
        "I was responsible for reducing patient wait times, because satisfaction scores had dropped to the lowest in the region.",
        "That's a complete Task in one sentence.",
        '...',
        "One important nuance.",
        "Even when the work was truly collaborative, you can still own your piece.",
        "While the team worked on the technical solution, my specific role was to manage client communications and set expectations.",
        "You're not lying or taking credit.",
        "You're focusing on YOUR contribution, which is exactly what the interviewer needs to hear.",
        '...',
        "Like Situation, Task should be brief.",
        "About ten percent of your answer.",
        "One to two sentences that clearly establish what you owned.",
        "Then move quickly into Action, where the real story begins.",
      ],
      keyTakeaways: [
        'Use "I" not "we" \u2014 define YOUR specific responsibility, not the team\'s',
        'Formula: "I was responsible for [deliverable] because [stakes]"',
        'Even in team efforts, focus on YOUR specific contribution',
      ],
      quiz: [
        {
          type: 'tf',
          question: 'In the Task section, it\'s fine to say "The team needed to..." instead of "I was responsible for..."',
          correctAnswer: false,
          explanation: 'Task should clearly define YOUR role. "The team needed to" hides your individual contribution. Use "I was responsible for..." to show ownership.',
        },
        {
          type: 'recall',
          question: 'What pronoun should dominate your Task (and Action) sections?',
          expectedAnswer: 'I',
          explanation: 'Use "I" consistently. "I was responsible for...", "I decided to...", "I led the effort to..." The interviewer is evaluating YOU, not your team.',
        },
        {
          type: 'mcq',
          question: 'Which Task statement is strongest?',
          options: [
            '"We needed to improve the process"',
            '"The department was struggling with efficiency"',
            '"I was tasked with reducing error rates by 50% because patient safety scores were declining"',
            '"There were some issues that needed addressing"',
          ],
          correctIndex: 2,
          explanation: 'Option C uses "I", specifies the deliverable (reduce errors by 50%), and includes stakes (patient safety scores declining). It\'s specific, owned, and consequential.',
        },
      ],
    },

    // ---- LESSON 2-3 ----
    {
      id: '2-3',
      title: 'Action: The Hero Section',
      duration: '5 min',
      audioScript: [
        "Welcome to the most important lesson in this entire course.",
        "Action is where interviews are won or lost.",
        "This section should be sixty percent of your answer, and it's where you prove your competency.",
        '...',
        "Let me show you the difference between a weak Action section and a strong one.",
        '...',
        "Weak version.",
        "I coordinated with the team and we worked together to solve the problem.",
        "We improved the process and things got better.",
        "That tells the interviewer absolutely nothing.",
        '...',
        "Strong version.",
        "First, I scheduled one-on-one meetings with each of the five department heads, to understand their specific pain points.",
        "Then, I created a shared project timeline in Asana, with weekly milestones and clear owners for each task.",
        "Finally, I set up Friday check-ins where each team lead reported progress, and I personally followed up with anyone who was falling behind.",
        '...',
        "The difference is what I call the zoom-in technique.",
        "Instead of describing things from thirty thousand feet, zoom in to ground level.",
        "What did you actually DO, step by step?",
        '...',
        "Here are three rules for a powerful Action section.",
        '...',
        "Rule one, use two to three specific action steps.",
        "Not one vague action. Not seven that blur together.",
        "Two to three concrete steps, described in detail.",
        "Think of it as, first I did this, then I did this, and finally I did this.",
        '...',
        "Rule two, replace vague verbs with vivid ones.",
        "Don't say managed. Say built, redesigned, discovered, or confronted.",
        "Don't say worked with. Say trained, mentored, persuaded, or rallied.",
        "Don't say helped. Say led, created, implemented, or resolved.",
        "Vivid verbs paint a picture. Vague verbs create fog.",
        '...',
        "Rule three, show your thinking, not just your doing.",
        "The interviewer wants to know WHY you chose those actions.",
        "I decided to start with one-on-one meetings rather than a group session, because I suspected people wouldn't speak openly in front of each other.",
        "That single sentence reveals your judgment, your emotional intelligence, and your strategic thinking.",
        "It's gold.",
        '...',
        "Here's a template for structuring your Action section.",
        "Step one, I decided to, action, because, reasoning.",
        "Step two, I then, action, which resulted in, interim outcome.",
        "Step three, Finally, I, action, to ensure, goal.",
        "This three-step structure with reasoning, creates an answer that feels thoughtful and complete.",
        '...',
        "When you practice, record yourself and listen back.",
        "Count your action steps.",
        "If you hear mostly vague verbs and team language, try again with the zoom-in technique.",
        "This one skill will set you apart from ninety percent of candidates.",
      ],
      keyTakeaways: [
        'Use the zoom-in technique: describe 2-3 specific action steps, not vague summaries',
        'Replace vague verbs (managed, helped, worked with) with vivid ones (built, confronted, redesigned)',
        'Show your THINKING \u2014 explain WHY you chose each action, not just what you did',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'Which demonstrates the "zoom-in technique"?',
          options: [
            '"I coordinated with the team to solve the problem"',
            '"I scheduled one-on-one meetings with each department head, created a shared timeline in Asana, and set up weekly check-ins"',
            '"I managed the project efficiently"',
            '"We all worked together and things improved"',
          ],
          correctIndex: 1,
          explanation: 'Option B zooms in to ground level with 3 specific, concrete actions: meetings, timeline creation, and weekly check-ins. The others stay at 30,000 feet.',
        },
        {
          type: 'tf',
          question: 'Explaining WHY you chose a particular action is unnecessary \u2014 interviewers only care about what you DID.',
          correctAnswer: false,
          explanation: 'Showing your reasoning ("I chose this approach because...") reveals judgment, emotional intelligence, and strategic thinking. It\'s one of the most impressive things a candidate can do.',
        },
        {
          type: 'apply',
          question: 'Think of an achievement. Can you describe it using the 3-step Action template? Step 1: "I decided to [action] because [reason]." Step 2: "I then [action]." Step 3: "Finally, I [action]."',
          prompt: 'Practice out loud if you can. The more you rehearse this 3-step structure, the more natural it becomes.',
        },
      ],
    },

    // ---- LESSON 2-4 ----
    {
      id: '2-4',
      title: 'Result: Proving Impact',
      duration: '4 min',
      audioScript: [
        "You've set the scene, defined your role, and described your actions.",
        "Now it's time to close the deal with Result.",
        "This is your chance to prove that your actions actually mattered.",
        '...',
        "The number one rule of the Result section? Quantify whenever possible.",
        "Numbers are the language of impact.",
        '...',
        "Here are ways to quantify your results.",
        "Revenue, we increased sales by twenty-three percent.",
        "Time, I reduced the onboarding process from three weeks to five days.",
        "Cost, this saved the department forty thousand dollars annually.",
        "Volume, our team processed sixty percent more requests per month.",
        "Satisfaction, patient satisfaction scores rose from 72 to 91.",
        "Scale, the solution was adopted across all twelve locations.",
        '...',
        "But what if you genuinely can't measure the outcome?",
        "Maybe it was a soft result like improved team morale. Or maybe the project is still ongoing.",
        "Here's what to do.",
        '...',
        "Use qualitative impact statements.",
        "My manager specifically praised the approach during our next review.",
        "The client renewed their contract and requested me for future projects.",
        "Three team members told me the new process was the best change we'd made all year.",
        "These aren't numbers, but they're concrete evidence of impact.",
        '...',
        "Now here's the secret weapon that most candidates miss.",
        "The lesson learned closer.",
        "After sharing your result, add one sentence about what you learned.",
        '...',
        "Looking back, I learned that proactive communication prevents most escalations.",
        "This experience taught me that building relationships before a crisis makes crisis management much easier.",
        "What I'd do differently next time is start the stakeholder alignment earlier.",
        '...',
        "The lesson learned shows three things interviewers love.",
        "Self-awareness, you can reflect honestly on your experience.",
        "Growth mindset, you're always learning and improving.",
        "And maturity, you don't just do things, you think about them.",
        '...',
        "One final tip.",
        "Your Result should take about twenty percent of your total answer.",
        "That's roughly thirty to forty seconds in a three-minute answer.",
        "State the outcome, quantify if possible, and close with what you learned.",
        "That's a perfect ending.",
      ],
      keyTakeaways: [
        'Quantify results whenever possible: revenue, time saved, cost reduced, satisfaction improved',
        'When you can\'t quantify, use qualitative evidence: manager praise, client renewals, team feedback',
        'Always end with a "lesson learned" \u2014 it shows self-awareness and growth mindset',
      ],
      quiz: [
        {
          type: 'recall',
          question: 'Name at least 3 ways to quantify a result in an interview answer.',
          expectedAnswer: 'Revenue/sales increase, time saved, cost reduced, volume/efficiency improved, satisfaction scores, scale of adoption',
          explanation: 'Common quantification methods: revenue growth, time savings, cost reduction, volume increase, satisfaction scores, scale (# of locations/users), error rate reduction.',
        },
        {
          type: 'tf',
          question: '"Things improved after that" is a strong enough Result statement.',
          correctAnswer: false,
          explanation: '"Things improved" is vague and unconvincing. A strong result is specific: "Error rates dropped 40% within the first month" or "The client renewed their $2M contract."',
        },
        {
          type: 'mcq',
          question: 'What should you include at the END of your Result section?',
          options: [
            'An apology for anything that went wrong',
            'A list of everyone who helped',
            'What you learned from the experience',
            'A request for the interviewer\'s feedback',
          ],
          correctIndex: 2,
          explanation: 'The "lesson learned closer" shows self-awareness and growth mindset. It\'s one of the highest-scoring elements interviewers look for.',
        },
      ],
    },

    // ---- LESSON 2-5 ----
    {
      id: '2-5',
      title: 'Putting STAR Together',
      duration: '4 min',
      audioScript: [
        "You've learned each STAR component individually.",
        "Now let's put them all together and see what a complete, polished answer sounds like.",
        '...',
        "I'm going to walk you through a full STAR answer, beat by beat.",
        "The question is, tell me about a time you had to manage a difficult team situation.",
        '...',
        "Here's the answer.",
        '...',
        "Situation.",
        "Last fall at my company, two team members were in constant conflict about project priorities, and it was starting to affect the entire team's output.",
        '...',
        "Task.",
        "As the project lead, I was responsible for resolving the conflict and getting us back on track for our Q4 deadline.",
        '...',
        "Action.",
        "First, I met with each person individually to understand their perspective without the other present.",
        "I discovered that the real issue wasn't priorities, it was that neither felt their expertise was being valued.",
        "Then, I redesigned our project roles so each person owned the area they were strongest in, with clear boundaries.",
        "Finally, I established a weekly sync where both would present their progress, giving each visibility and recognition.",
        '...',
        "Result.",
        "Within three weeks, the tension dropped noticeably.",
        "We hit our Q4 deadline two days early.",
        "And in our next team survey, collaboration scores went from 62 to 89.",
        "What I learned is that most conflicts aren't about the issue on the surface, they're about feeling valued.",
        '...',
        "Now let's analyze what made that answer work.",
        '...',
        "The Situation was two sentences, specific and high-stakes.",
        "The Task was one sentence, clearly owned with I.",
        "The Action had three distinct steps, each with reasoning.",
        "And the Result had a number, a timeline, and a lesson learned.",
        '...',
        "Notice the transitions.",
        "You don't need fancy transition phrases.",
        "Simple words work, first, then, finally.",
        "These signal to the interviewer that your answer is structured.",
        '...',
        "One technique I call the bookend.",
        "Start your answer with a brief hook that previews the outcome.",
        "I resolved a team conflict that was threatening our Q4 deadline.",
        "Then tell the full STAR story.",
        "The bookend gives the interviewer a reason to listen, they already know it ends well.",
        '...',
        "Congratulations, you've completed Module Two.",
        "You now understand each STAR component at a deep level.",
        "Situation sets the scene. Task shows ownership. Action proves competency. Result demonstrates impact.",
        "In Module Three, we'll apply this framework to specific question types.",
      ],
      keyTakeaways: [
        'A complete STAR answer: 2-sentence Situation, 1-sentence Task, 3-step Action with reasoning, quantified Result with lesson learned',
        'Use simple transitions (First, Then, Finally) to signal structure',
        'The "bookend" technique: preview the outcome at the start to hook the interviewer\'s attention',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What is the "bookend" technique?',
          options: [
            'Starting and ending your answer with the same phrase',
            'Previewing the positive outcome at the start of your answer to hook the listener',
            'Bookmarking important stories in your notes',
            'Answering the question twice for emphasis',
          ],
          correctIndex: 1,
          explanation: 'The bookend technique hooks the interviewer by previewing the outcome upfront: "I resolved a team conflict that was threatening our Q4 deadline." Then you tell the full story.',
        },
        {
          type: 'apply',
          question: 'Think of one of your stories. Try mentally walking through the complete STAR structure: 2-sentence Situation, 1-sentence Task, 3-step Action, quantified Result + lesson learned.',
          prompt: 'If you can do this in your head, try it out loud next. The transition from mental rehearsal to verbal practice is where real improvement happens.',
        },
        {
          type: 'tf',
          question: 'You need sophisticated transition phrases between STAR sections to sound professional.',
          correctAnswer: false,
          explanation: 'Simple transitions like "First," "Then," and "Finally" work perfectly. They signal structure without sounding rehearsed. Fancy transitions can actually sound unnatural.',
        },
      ],
    },
  ],
};


// ============================================================
// MODULE 3: QUESTION TYPE MASTERY
// ============================================================

const module3 = {
  id: 3,
  title: 'Question Type Mastery',
  icon: '\uD83C\uDFD3',
  description: 'Nail every question type from "Tell me about yourself" to tough curveballs',
  lessons: [
    // ---- LESSON 3-1 ----
    {
      id: '3-1',
      title: '"Tell Me About Yourself"',
      duration: '4 min',
      audioScript: [
        "This is the most common interview question, and most people blow it.",
        "They either recite their entire resume, or they ramble for five minutes.",
        "Let's fix that.",
        '...',
        "Tell me about yourself, is not an invitation to share your life story.",
        "It's really asking, give me a relevant, concise overview that makes me want to learn more.",
        '...',
        "Use the three-act structure.",
        "Act one, your past. Where you started and what shaped you.",
        "Act two, your present. What you do now and what you're great at.",
        "Act three, your future. Why you're here and what excites you about this opportunity.",
        '...',
        "Each act should be about thirty seconds.",
        "Total answer, sixty to ninety seconds. No more.",
        '...',
        "Here's an example.",
        "Act one. I started my career in customer service, where I discovered I had a natural ability to solve complex problems under pressure.",
        "Act two. For the past three years, I've been a project manager at a healthcare company, where I've led cross-functional teams and reduced project cycle times by thirty percent.",
        "Act three. I'm excited about this role because it combines my problem-solving skills with my passion for healthcare innovation, and your focus on patient-centered technology is exactly the direction I want to grow in.",
        '...',
        "Notice what's NOT in that answer.",
        "No childhood history. No list of every job. No generic filler like, I'm a hard worker and a team player.",
        '...',
        "Three mistakes to avoid.",
        "First, don't start with, well, I was born in. Start with your professional story.",
        "Second, don't list every job. Pick the highlights that are relevant to THIS role.",
        "Third, don't end without connecting to the company. Act three should clearly explain why you're sitting in this specific interview.",
        '...',
        "Here's a pro tip.",
        "Customize act three for every company.",
        "Acts one and two can stay the same.",
        "But act three should reference something specific about the company or role.",
        "It shows you've done your research and you're intentional about your career.",
      ],
      keyTakeaways: [
        'Use the 3-act structure: Past (what shaped you), Present (what you do now), Future (why this role)',
        'Keep it 60-90 seconds total \u2014 no resume recitals or life stories',
        'Customize Act 3 for every company \u2014 it shows research and intention',
      ],
      quiz: [
        {
          type: 'recall',
          question: 'What are the 3 acts in the "Tell Me About Yourself" structure?',
          expectedAnswer: 'Past, Present, Future',
          explanation: 'Act 1: Past (where you started), Act 2: Present (what you do now), Act 3: Future (why this role/company). Each about 30 seconds, total 60-90 seconds.',
        },
        {
          type: 'tf',
          question: 'You should start your "Tell Me About Yourself" answer with where you were born and grew up.',
          correctAnswer: false,
          explanation: 'Start with your professional story, not your personal history. The interviewer wants relevant career highlights, not a biography.',
        },
        {
          type: 'mcq',
          question: 'Which part of your "Tell Me About Yourself" should be customized for EACH company?',
          options: [
            'Act 1 \u2014 your past experience',
            'Act 2 \u2014 your current role',
            'Act 3 \u2014 why this specific role/company excites you',
            'All three acts need to change completely',
          ],
          correctIndex: 2,
          explanation: 'Acts 1 and 2 can remain consistent. Act 3 should reference something specific about the company or role to show you\'ve done research.',
        },
      ],
    },

    // ---- LESSON 3-2 ----
    {
      id: '3-2',
      title: 'Behavioral Questions',
      duration: '4 min',
      audioScript: [
        "Tell me about a time when, is the signature phrase of behavioral questions.",
        "You'll hear it over and over.",
        "Tell me about a time you showed leadership.",
        "Tell me about a time you handled conflict.",
        "Tell me about a time you failed.",
        "These are the bread and butter of modern interviews.",
        '...',
        "The good news? You already have the framework. STAR handles all of these.",
        "The skill now is matching the right story to the right question.",
        '...',
        "Here's the story mapping technique.",
        "Take your seven to ten core stories.",
        "For each story, list the competencies it demonstrates.",
        "Leadership, teamwork, conflict resolution, problem-solving, adaptability, initiative.",
        "Most stories demonstrate three to five competencies.",
        '...',
        "When you hear a behavioral question, mentally scan your story bank.",
        "Which story best demonstrates the competency being asked about?",
        "You don't need a different story for every question.",
        "You need the right story for the right competency.",
        '...',
        "Let's talk about the tricky ones.",
        '...',
        "Tell me about a time you failed.",
        "Pick a real failure, not a humble brag.",
        "I worked too hard, is not a failure.",
        "Choose something genuine, show what you did about it, and emphasize the lesson learned.",
        "This question tests self-awareness, not perfection.",
        '...',
        "Tell me about a time you disagreed with your manager.",
        "Don't trash your manager. Show respect while demonstrating professional courage.",
        "I presented my perspective with data, listened to their reasoning, and we found a compromise.",
        "Even if you ultimately deferred, showing that you advocate professionally is what matters.",
        '...',
        "Tell me about a conflict with a coworker.",
        "Choose a conflict that was resolved positively.",
        "Focus on understanding the other person's perspective, not on winning.",
        "The best answers show empathy and communication skills.",
        '...',
        "One universal tip for all behavioral questions.",
        "When in doubt, pick the story where your individual actions are most clear and the impact is most measurable.",
        "That's always the strongest choice.",
      ],
      keyTakeaways: [
        'Map each of your 7-10 stories to the competencies they demonstrate \u2014 most stories cover 3-5 questions',
        'For failure questions: pick a real failure, show what you did about it, emphasize the lesson',
        'When in doubt, pick the story with the clearest individual actions and most measurable impact',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'When asked about a conflict, which approach is strongest?',
          options: [
            'Show that you were right and the other person was wrong',
            'Say you\'ve never really had conflicts at work',
            'Focus on understanding the other perspective and finding a resolution',
            'Describe how your manager stepped in to fix it',
          ],
          correctIndex: 2,
          explanation: 'Conflict questions test empathy and communication. The strongest answers show you sought to understand the other perspective and worked toward a positive resolution.',
        },
        {
          type: 'tf',
          question: 'For "tell me about a failure" questions, saying "I worked too hard" is a good approach.',
          correctAnswer: false,
          explanation: 'Interviewers see through humble brags. Pick a genuine failure, take ownership, describe what you did about it, and emphasize the lesson. Authenticity scores higher than perfection.',
        },
        {
          type: 'apply',
          question: 'Pick one of your career stories. How many different question types could it answer? Think about: leadership, teamwork, conflict, problem-solving, adaptability, and initiative.',
          prompt: 'Try to map it to at least 3 different competencies. If you can, you have a truly versatile story.',
        },
      ],
    },

    // ---- LESSON 3-3 ----
    {
      id: '3-3',
      title: 'Situational Questions',
      duration: '3 min',
      audioScript: [
        "Situational questions start with, what would you do if.",
        "What would you do if a team member wasn't pulling their weight?",
        "How would you handle an angry customer?",
        "What would you do if you disagreed with a company policy?",
        "These are hypothetical, not behavioral.",
        '...',
        "But here's the secret.",
        "You should still use real experience to answer them.",
        '...',
        "Instead of purely theorizing, anchor your answer in something real.",
        "Here's the formula.",
        "Start with your approach, then illustrate with a real example.",
        '...',
        "My approach would be to first understand the root cause, then address it directly. In fact, I had a similar situation last year where a team member was struggling with their workload.",
        "Then tell the STAR story.",
        "This transforms a hypothetical answer into a credible one backed by evidence.",
        '...',
        "The interviewer is testing two things with situational questions.",
        "First, your judgment. Do you have sound instincts?",
        "Second, your experience. Have you actually dealt with situations like this?",
        '...',
        "By starting with your approach and then backing it with a real example, you demonstrate both.",
        '...',
        "One mistake to avoid, don't give a textbook answer without any personal experience.",
        "I would follow company policy and escalate through proper channels, sounds robotic.",
        "I believe in addressing concerns directly. Last year, I noticed a policy that was creating bottlenecks, so I, dot dot dot.",
        "That sounds human, experienced, and thoughtful.",
        '...',
        "Bottom line, even when the question is hypothetical, your answer should be grounded in reality.",
        "What would you do? becomes What DID you do in a similar situation.",
        "That's always more convincing.",
      ],
      keyTakeaways: [
        'Formula: State your approach first, then illustrate with a real experience ("In fact, I had a similar situation...")',
        'Situational questions test both judgment AND experience \u2014 show both',
        'Avoid robotic textbook answers \u2014 ground every hypothetical in something real you\'ve done',
      ],
      quiz: [
        {
          type: 'tf',
          question: 'You can reference a real past experience when answering a hypothetical "what would you do" question.',
          correctAnswer: true,
          explanation: 'Absolutely! The strongest approach is: state your approach, then say "In fact, I had a similar situation where..." and tell a real STAR story. This proves you have actual experience.',
        },
        {
          type: 'mcq',
          question: 'What are interviewers testing with situational "what would you do" questions?',
          options: [
            'Your creativity and imagination',
            'Your judgment AND your experience',
            'Whether you\'ve memorized company policies',
            'How quickly you can think on your feet',
          ],
          correctIndex: 1,
          explanation: 'Situational questions test both your judgment (do you have good instincts?) and your experience (have you dealt with this before?). Anchoring in real experience demonstrates both.',
        },
        {
          type: 'recall',
          question: 'What is the formula for answering situational questions?',
          expectedAnswer: 'State your approach, then illustrate with a real example',
          explanation: 'Formula: "My approach would be to [approach]. In fact, I had a similar situation where [real STAR story]." This combines sound judgment with proven experience.',
        },
      ],
    },

    // ---- LESSON 3-4 ----
    {
      id: '3-4',
      title: '"Why This Role/Company?"',
      duration: '4 min',
      audioScript: [
        "Why do you want to work here?",
        "This question feels simple, but it's where many candidates stumble.",
        "A generic answer reveals that you haven't done your homework.",
        "A great answer shows genuine alignment between your goals and the company's mission.",
        '...',
        "First, what NOT to say.",
        "I'm looking for new opportunities. That's about you, not them.",
        "I heard you have great benefits. That's transactional, not passionate.",
        "I just want to work somewhere stable. That signals you'd take any job.",
        '...',
        "Instead, research three things before every interview.",
        '...',
        "Thing one, the company's mission or recent achievements.",
        "Read their about page, recent press releases, or LinkedIn posts.",
        "Find something specific that resonates with you.",
        '...',
        "Thing two, the role's actual responsibilities.",
        "Read the job description carefully.",
        "Identify the two or three most important requirements.",
        "Connect them to your experience.",
        '...',
        "Thing three, something that excites you about their direction.",
        "Are they launching a new product? Expanding to new markets? Investing in innovation?",
        "Showing you know where they're headed, demonstrates strategic thinking.",
        '...',
        "Here's a template.",
        "What excites me about this role is, specific aspect of the role.",
        "I've been following your, specific company initiative, and it aligns with my experience in, your relevant skill.",
        "I see this as an opportunity to, your contribution, while growing in, your development area.",
        '...',
        "This template works because it checks three boxes.",
        "You know the role. You know the company. And you've thought about how you add value.",
        '...',
        "One pro tip.",
        "If you can name a specific person, product, or initiative, you immediately stand out.",
        "I was really impressed by your CEO's recent talk about patient-centered technology, is infinitely better than, I like your company culture.",
        "Specificity signals genuine interest.",
      ],
      keyTakeaways: [
        'Research 3 things: company mission/achievements, role responsibilities, and their future direction',
        'Template: "What excites me is [role aspect]. I\'ve followed your [initiative]. I\'d contribute [value] while growing in [area]"',
        'Name a specific person, product, or initiative \u2014 specificity signals genuine interest',
      ],
      quiz: [
        {
          type: 'recall',
          question: 'Name the 3 things you should research before answering "Why this company?"',
          expectedAnswer: 'Company mission/achievements, role responsibilities, company direction/future',
          explanation: 'Research: (1) Mission or recent achievements, (2) Actual role responsibilities from the JD, (3) Where the company is headed. Connect all three to your experience.',
        },
        {
          type: 'mcq',
          question: 'Which "Why this company?" answer is strongest?',
          options: [
            '"I\'m looking for a new challenge and this seems like a great fit"',
            '"I heard you have excellent benefits and work-life balance"',
            '"Your CEO\'s recent initiative on patient-centered tech aligns with my 3 years of healthcare UX experience"',
            '"I want to work at a stable, growing company"',
          ],
          correctIndex: 2,
          explanation: 'Option C names something specific (CEO\'s initiative), connects it to personal experience (healthcare UX), and shows genuine research. The others are generic.',
        },
        {
          type: 'apply',
          question: 'Think about a company you\'d like to work for. Can you name one specific initiative, product, or leader that excites you? That\'s the foundation of a great "Why this company?" answer.',
          prompt: 'If you can\'t name something specific, that\'s a sign you need to do more research before the interview.',
        },
      ],
    },

    // ---- LESSON 3-5 ----
    {
      id: '3-5',
      title: 'Questions to Ask THEM',
      duration: '3 min',
      audioScript: [
        "Do you have any questions for us?",
        "This isn't small talk. It's the final test.",
        "Asking no questions, or asking weak ones, can undo an otherwise great interview.",
        '...',
        "There are three types of smart questions.",
        '...',
        "Type one, role questions.",
        "These show you're thinking seriously about doing the job well.",
        "What does success look like in the first ninety days?",
        "What's the biggest challenge the person in this role will face?",
        "How is performance measured and reviewed?",
        '...',
        "Type two, team and culture questions.",
        "These show you're thinking about fit and collaboration.",
        "How would you describe the team dynamic?",
        "What do people enjoy most about working here?",
        "How does the team handle disagreements or conflicting priorities?",
        '...',
        "Type three, strategic questions.",
        "These show you think like a leader, not just an employee.",
        "What's the company's biggest priority for the next year?",
        "How does this role contribute to the broader organizational goals?",
        "What keeps you excited about working here?",
        '...',
        "Prepare three to five questions, because some may get answered during the interview.",
        "Mix types, one role question, one culture question, one strategic question.",
        '...',
        "Questions to NEVER ask.",
        "How much vacation do I get? Not in the first interview.",
        "What does the company do? Shows you didn't research.",
        "Did I get the job? Puts them on the spot.",
        '...',
        "One powerful technique.",
        "Reference something from the interview itself.",
        "You mentioned earlier that the team is going through a reorganization. How do you see this role evolving as that takes shape?",
        "This shows you were actively listening, and that's deeply impressive.",
        '...',
        "Module Three is complete.",
        "You now know how to handle the five most common question types.",
        "In Module Four, we'll cover advanced techniques that separate good candidates from great ones.",
      ],
      keyTakeaways: [
        '3 types of smart questions: Role (success metrics), Culture (team dynamics), Strategic (company direction)',
        'Prepare 3-5 questions and mix types \u2014 some will get answered during the interview',
        'Reference something from the interview itself \u2014 it shows you were actively listening',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'Which type of question impresses interviewers the most?',
          options: [
            'Questions about salary and benefits',
            'Questions about the company\'s founding story',
            'Strategic questions about the company\'s priorities and direction',
            'Questions about the interview timeline',
          ],
          correctIndex: 2,
          explanation: 'Strategic questions ("What\'s the company\'s biggest priority next year?") show you think like a leader. They signal that you\'re evaluating the opportunity, not just hoping to be picked.',
        },
        {
          type: 'recall',
          question: 'What are the 3 types of smart questions to ask at the end of an interview?',
          expectedAnswer: 'Role questions, Team/Culture questions, Strategic questions',
          explanation: 'Mix all three: (1) Role questions about success metrics and challenges, (2) Culture questions about team dynamics, (3) Strategic questions about company priorities and direction.',
        },
        {
          type: 'tf',
          question: 'Referencing something the interviewer said earlier in the conversation is a powerful question technique.',
          correctAnswer: true,
          explanation: 'Referencing earlier conversation shows active listening and genuine engagement. "You mentioned X earlier \u2014 how does that affect Y?" is one of the most impressive things a candidate can do.',
        },
      ],
    },
  ],
};


// ============================================================
// MODULE 4: ADVANCED TECHNIQUES
// ============================================================

const module4 = {
  id: 4,
  title: 'Advanced Techniques',
  icon: '\uD83D\uDE80',
  description: 'Elite strategies that separate good candidates from unforgettable ones',
  lessons: [
    // ---- LESSON 4-1 ----
    {
      id: '4-1',
      title: 'The Story Bank Method',
      duration: '4 min',
      audioScript: [
        "Welcome to Module Four, advanced techniques.",
        "Let's start with the most powerful interview prep strategy that exists.",
        "The Story Bank method.",
        '...',
        "Here's the core insight.",
        "You don't prepare answers. You prepare stories.",
        "Seven to ten versatile stories can cover forty to fifty different questions.",
        "This is how professional interview coaches work, and it's a game changer.",
        '...',
        "Here's how to build your story bank.",
        '...',
        "Step one, brainstorm your career highlights.",
        "Think about times you led something, solved a problem, handled conflict, went above and beyond, learned from failure, adapted to change.",
        "Write down every significant experience you can remember.",
        "Aim for fifteen to twenty raw stories.",
        '...',
        "Step two, select the seven to ten strongest.",
        "Choose stories that are recent, within the last three to five years.",
        "Choose stories where YOUR actions were central.",
        "Choose stories with measurable outcomes.",
        "And choose stories that cover different competencies.",
        '...',
        "Step three, map each story to competencies.",
        "For each story, list every competency it demonstrates.",
        "Your story about leading a crisis response might cover, leadership, decision-making under pressure, communication, teamwork, and adaptability.",
        "That's five questions from one story.",
        '...',
        "Step four, structure each story in STAR format.",
        "Write out the key beats, not a script, but the main points.",
        "Situation in two sentences.",
        "Task in one sentence.",
        "Three action steps with reasoning.",
        "Quantified result with lesson learned.",
        '...',
        "Step five, practice each story out loud until it's natural.",
        "Not memorized, natural.",
        "You should be able to tell each story conversationally, adapting the emphasis based on which question you're answering.",
        '...',
        "Here's the magic.",
        "When you hear a question like, tell me about a time you showed leadership, you don't panic.",
        "You think, that's my crisis response story. I'll emphasize the decision-making parts.",
        "Same story, but you adjust the angle for the question.",
        "This is how professionals do it.",
        "This app has a Story Bank feature, where you can build and practice your stories.",
        "Use it. It's the single highest-value prep activity you can do.",
      ],
      keyTakeaways: [
        '7-10 versatile stories can cover 40-50 different interview questions',
        'Build your bank: brainstorm 15-20 experiences, select the strongest, map each to competencies',
        'Don\'t memorize scripts \u2014 know your stories well enough to adapt the emphasis for any question',
      ],
      quiz: [
        {
          type: 'recall',
          question: 'How many core stories should you prepare for your Story Bank?',
          expectedAnswer: '7 to 10',
          explanation: '7-10 stories is the sweet spot. Each story typically covers 3-5 competencies, giving you coverage for 40-50 different questions without memorizing individual answers.',
        },
        {
          type: 'mcq',
          question: 'What criteria should you use when selecting stories for your bank?',
          options: [
            'The most dramatic stories, regardless of your role',
            'Stories from your very first job for maximum experience range',
            'Recent stories where YOUR actions were central and outcomes were measurable',
            'Stories that make your previous employers look bad',
          ],
          correctIndex: 2,
          explanation: 'Best stories are: recent (3-5 years), YOUR actions are central, outcomes are measurable, and they cover different competencies.',
        },
        {
          type: 'apply',
          question: 'Right now, try to list 3 career stories you could include in your Story Bank. For each, name at least 2 competencies it demonstrates.',
          prompt: 'Think about: times you led something, solved a problem, handled conflict, went above and beyond, adapted to change, or learned from failure.',
        },
      ],
    },

    // ---- LESSON 4-2 ----
    {
      id: '4-2',
      title: 'Bridge Answers',
      duration: '3 min',
      audioScript: [
        "Sometimes you get a question and your mind goes blank.",
        "Or the question is about a competency where your experience is thin.",
        "That's when you need a bridge answer.",
        '...',
        "A bridge answer uses the acknowledge, bridge, deliver technique.",
        '...',
        "Step one, acknowledge the question.",
        "Show you understood what was asked.",
        "That's a great question about managing remote teams.",
        '...',
        "Step two, bridge to your strength.",
        "Pivot naturally to an area where you have strong experience.",
        "While I haven't managed a fully remote team, I've led a distributed team across three offices, which presented many of the same challenges.",
        '...',
        "Step three, deliver your STAR story.",
        "Now tell your story with confidence.",
        '...',
        "The bridge works because you're not avoiding the question.",
        "You're honestly acknowledging the gap, while demonstrating that you have relevant transferable experience.",
        "Interviewers respect honesty combined with adaptability.",
        '...',
        "Here's the key distinction.",
        "Bridging is NOT dodging.",
        "Dodging means ignoring the question entirely and talking about something unrelated.",
        "Bridging means connecting the question to your closest relevant experience.",
        "The connection must be genuine and logical.",
        '...',
        "Another use for bridge answers, when the question is uncomfortably specific.",
        "Tell me about a time you managed a budget over one million dollars.",
        "If your budgets were smaller, bridge.",
        "My largest budget was three hundred thousand, but the principles of budget management are the same. Let me tell you how I cut costs by twenty percent.",
        '...',
        "The bridge technique gives you permission to answer from your strength, without pretending to have experience you don't have.",
        "Authenticity plus transferable skills is a winning combination.",
      ],
      keyTakeaways: [
        'Bridge technique: Acknowledge the question \u2192 Bridge to your closest relevant experience \u2192 Deliver your STAR story',
        'Bridging is NOT dodging \u2014 the connection must be genuine and logical',
        'Authenticity + transferable skills beats pretending to have exact experience',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What is a "bridge answer"?',
          options: [
            'Avoiding the question entirely and changing the topic',
            'Acknowledging the question, then pivoting to your closest relevant experience',
            'Asking the interviewer to rephrase the question',
            'Giving a very short answer to move on quickly',
          ],
          correctIndex: 1,
          explanation: 'A bridge answer acknowledges the question honestly, then naturally pivots to relevant transferable experience. It\'s honest, not evasive.',
        },
        {
          type: 'tf',
          question: 'It\'s okay to redirect an interview question to a different topic where you have stronger experience, as long as the connection is genuine.',
          correctAnswer: true,
          explanation: 'Bridge answers are a legitimate and respected technique. The key is that the connection must be genuine and logical \u2014 "While I haven\'t done X, I have done Y which involved similar challenges."',
        },
        {
          type: 'recall',
          question: 'What are the 3 steps of the bridge technique?',
          expectedAnswer: 'Acknowledge, Bridge, Deliver',
          explanation: '(1) Acknowledge the question, (2) Bridge to your relevant experience with a natural pivot, (3) Deliver your STAR story with confidence.',
        },
      ],
    },

    // ---- LESSON 4-3 ----
    {
      id: '4-3',
      title: 'Panel Interview Tactics',
      duration: '4 min',
      audioScript: [
        "Panel interviews are intimidating.",
        "Three, four, sometimes five interviewers, all watching you at once.",
        "But with the right tactics, you can actually make the panel format work in your favor.",
        '...',
        "Tactic one, the eye contact rotation.",
        "When someone asks you a question, start your answer by making eye contact with them.",
        "After your first sentence or two, naturally shift your gaze to include the other panel members.",
        "Then return to the questioner for your conclusion.",
        "This makes everyone feel included while honoring the person who asked.",
        '...',
        "Tactic two, address the room, not just the questioner.",
        "Some candidates get tunnel vision and only talk to whoever asked.",
        "The other panel members feel ignored, and their scores suffer.",
        "Think of it like presenting to a group, not having a one-on-one conversation.",
        '...',
        "Tactic three, identify the decision maker.",
        "There's usually one person whose opinion carries the most weight.",
        "Often it's the hiring manager, or the most senior person in the room.",
        "Give them slightly more eye contact without ignoring others.",
        "And make sure your strongest points land while looking at them.",
        '...',
        "Tactic four, handle rapid-fire questions calmly.",
        "In some panels, questions come fast from different people.",
        "Don't rush. Take a beat before each answer.",
        "A brief pause shows composure, not hesitation.",
        "It's better to pause for two seconds and give a structured answer, than to blurt out an unorganized response.",
        '...',
        "Tactic five, use names.",
        "If introductions were made, try to use panel members' names.",
        "As Dr. Chen mentioned earlier, and Building on what Sarah asked.",
        "This shows attention, respect, and social intelligence.",
        "If you're bad with names, write them down at the start.",
        '...',
        "One final tip.",
        "Before the interview, ask how many people will be on the panel.",
        "Prepare enough copies of your materials for everyone.",
        "And bring a small notepad, it's perfectly acceptable to take brief notes during a panel interview.",
        "It actually signals that you value what each person is saying.",
      ],
      keyTakeaways: [
        'Eye contact rotation: start with the questioner, sweep the room, return to questioner for your conclusion',
        'Identify the decision maker \u2014 give them slightly more attention without ignoring others',
        'Use panel members\' names when possible \u2014 it shows attention and social intelligence',
      ],
      quiz: [
        {
          type: 'recall',
          question: 'When answering a panel question, who should you make eye contact with?',
          expectedAnswer: 'Start with the questioner, sweep to include all panel members, return to the questioner for your conclusion',
          explanation: 'The eye contact rotation: Begin with the person who asked (respect), sweep the room (inclusion), return to the questioner for your closing (connection).',
        },
        {
          type: 'mcq',
          question: 'What\'s the best strategy when panel members ask rapid-fire questions?',
          options: [
            'Answer as quickly as possible to show you can think fast',
            'Ask them to slow down',
            'Take a brief 2-second pause before each answer to collect your thoughts',
            'Only answer the most important-seeming questions',
          ],
          correctIndex: 2,
          explanation: 'A brief pause shows composure, not hesitation. It\'s always better to pause for 2 seconds and give a structured answer than to blurt out something disorganized.',
        },
        {
          type: 'tf',
          question: 'Writing down panel members\' names at the start of the interview is unprofessional.',
          correctAnswer: false,
          explanation: 'It\'s perfectly professional and actually impressive. Using names later ("As Dr. Chen mentioned...") shows attention and social intelligence. A small notepad is always acceptable.',
        },
      ],
    },

    // ---- LESSON 4-4 ----
    {
      id: '4-4',
      title: 'Handling Curveball Questions',
      duration: '3 min',
      audioScript: [
        "What happens when you get a question you didn't prepare for?",
        "Your mind goes blank. Your palms get sweaty.",
        "It happens to everyone.",
        "Here's how to handle it gracefully.",
        '...',
        "First, the buy time technique.",
        "You are allowed to think.",
        "Say one of these phrases, and then take five to ten seconds to gather your thoughts.",
        "That's a really thoughtful question. Let me think about the best example.",
        "I want to give you a strong answer for this. Give me just a moment.",
        "Great question. Let me consider which experience best illustrates that.",
        '...',
        "These phrases are not stalling. They're showing the interviewer that you're thoughtful and intentional.",
        "Silence after a question feels like an eternity to you, but to the interviewer, five seconds of silence shows you're taking the question seriously.",
        '...',
        "Second, use the bridge technique from our earlier lesson.",
        "If you don't have an exact example, find the closest one.",
        "I haven't experienced that exact scenario, but I had a situation that was similar in a key way.",
        '...',
        "Third, when nothing comes to mind, be honest with structure.",
        "I haven't encountered that specific situation yet. But if I did, here's how I would approach it.",
        "Then walk through your thinking process using a logical framework.",
        "First, I'd assess the situation. Then, I'd identify the stakeholders. Then, I'd develop a plan.",
        "Showing structured thinking is sometimes more impressive than having the perfect story.",
        '...',
        "What about truly weird questions?",
        "How many tennis balls fit in this room? If you were an animal, what would you be?",
        "These test how you think, not what you know.",
        "Talk through your reasoning out loud.",
        "Show your problem-solving process.",
        "There's rarely a right answer, there's only a right approach.",
        '...',
        "Remember, interviewers have seen thousands of candidates.",
        "They don't expect perfection.",
        "They expect composure, honesty, and structured thinking.",
        "A graceful recovery from a tough question is more impressive than a perfect answer to an easy one.",
      ],
      keyTakeaways: [
        'Buy time gracefully: "That\'s a thoughtful question. Let me think about the best example." Then pause 5-10 seconds.',
        'When nothing comes to mind: be honest, then walk through structured thinking ("First I\'d assess, then I\'d identify...")',
        'A graceful recovery from a tough question impresses more than a perfect answer to an easy one',
      ],
      quiz: [
        {
          type: 'tf',
          question: '"I don\'t know" is always a bad answer in an interview.',
          correctAnswer: false,
          explanation: '"I haven\'t encountered that specific situation, but here\'s how I\'d approach it..." is perfectly acceptable and can be impressive. Honest acknowledgment + structured thinking beats making something up.',
        },
        {
          type: 'mcq',
          question: 'What should you do when your mind goes blank on a question?',
          options: [
            'Say the first thing that comes to mind',
            'Ask to skip the question',
            'Use a buy-time phrase and take 5-10 seconds to think',
            'Redirect to a completely different topic',
          ],
          correctIndex: 2,
          explanation: 'A buy-time phrase ("That\'s a great question, let me think...") followed by a brief pause shows composure and intentionality. 5-10 seconds feels long to you but normal to the interviewer.',
        },
        {
          type: 'apply',
          question: 'Practice saying this out loud right now: "That\'s a really thoughtful question. Let me think about the best example." Then pause for 5 seconds. Did the silence feel uncomfortable? That\'s normal \u2014 it gets easier with practice.',
          prompt: 'The buy-time technique only works if you\'ve practiced it. The more you rehearse it, the more natural it feels when you need it.',
        },
      ],
    },

    // ---- LESSON 4-5 ----
    {
      id: '4-5',
      title: 'The 3-Minute Rule',
      duration: '3 min',
      audioScript: [
        "This is your final lesson, and it might be the most practical tip in the entire course.",
        "The three-minute rule.",
        '...',
        "Most interview answers should be between two and three minutes long.",
        "Under two minutes, and you probably haven't given enough detail.",
        "Over four minutes, and you've likely lost the interviewer's attention.",
        '...',
        "Here's why three minutes is the sweet spot.",
        "It's long enough to tell a complete STAR story with specific details.",
        "But short enough to keep the interviewer engaged and leave room for follow-up questions.",
        '...',
        "How do you know when you've hit three minutes without looking at a clock?",
        "Use the natural structure of STAR as your guide.",
        '...',
        "Situation, about twenty seconds.",
        "Task, about fifteen seconds.",
        "Action, about one minute forty seconds.",
        "Result, about forty-five seconds.",
        "That adds up to three minutes.",
        '...',
        "Here's the wrap-up signal technique.",
        "When you feel yourself approaching the end of your answer, use a closing phrase.",
        "So the end result was.",
        "The key outcome from that experience was.",
        "What I learned from this was.",
        "These phrases signal to the interviewer that you're wrapping up.",
        "It's like a verbal period at the end of a sentence.",
        '...',
        "Without a wrap-up signal, answers tend to trail off.",
        "And then, yeah, it worked out well. So, um, that's basically what happened.",
        "That's a weak ending that undermines everything before it.",
        '...',
        "Instead, land with confidence.",
        "The end result was a twenty-three percent improvement in efficiency, and I learned that early stakeholder alignment saves weeks of rework down the line.",
        "That's a clean, confident close.",
        '...',
        "One more tip for controlling your answer length.",
        "If you notice you've been talking for a while, it's perfectly fine to check in.",
        "Would you like me to go into more detail on any part of that?",
        "This shows self-awareness and gives the interviewer control.",
        '...',
        "Congratulations.",
        "You've completed all four modules.",
        "You now have a complete toolkit, STAR framework, story bank, question type strategies, and advanced techniques.",
        "The only thing left is practice.",
        "Every time you practice out loud, you get better.",
        "You've got this.",
      ],
      keyTakeaways: [
        'Ideal answer length is 2-3 minutes: enough for a complete STAR story, short enough to keep attention',
        'Use wrap-up signals: "The key outcome was..." or "What I learned was..." to close confidently',
        'Check in if unsure: "Would you like me to go into more detail?" shows self-awareness',
      ],
      quiz: [
        {
          type: 'mcq',
          question: 'What is the ideal length for most interview answers?',
          options: [
            '30 seconds to 1 minute',
            '2 to 3 minutes',
            '5 to 7 minutes',
            'As long as it takes to cover everything',
          ],
          correctIndex: 1,
          explanation: '2-3 minutes is the sweet spot. It\'s long enough for a complete STAR story with specific details, but short enough to keep the interviewer engaged and leave room for follow-ups.',
        },
        {
          type: 'recall',
          question: 'What is the "wrap-up signal" technique?',
          expectedAnswer: 'Using closing phrases like "The key outcome was..." or "What I learned was..." to signal you\'re ending your answer',
          explanation: 'Wrap-up signals are verbal cues that tell the interviewer you\'re concluding: "So the end result was...", "The key outcome was...", "What I learned from this was..." They create a clean, confident close.',
        },
        {
          type: 'apply',
          question: 'You\'ve completed the entire course! Before your next practice session, pick your top 3 takeaways from all 20 lessons. What will you focus on improving first?',
          prompt: 'The course taught you frameworks, but practice makes them yours. Open Practice Mode and try applying what you\'ve learned to a real question.',
        },
      ],
    },
  ],
};


// ============================================================
// EXPORT: All modules
// ============================================================

export const LEARNING_MODULES = [module1, module2, module3, module4];

/**
 * Get a specific lesson by its ID (e.g., "2-3")
 */
export function getLessonById(lessonId) {
  for (const mod of LEARNING_MODULES) {
    const lesson = mod.lessons.find(l => l.id === lessonId);
    if (lesson) return { module: mod, lesson };
  }
  return null;
}

/**
 * Get the next lesson after a given lesson ID
 * Returns null if the given lesson is the last one
 */
export function getNextLesson(currentLessonId) {
  const allLessons = LEARNING_MODULES.flatMap(m =>
    m.lessons.map(l => ({ moduleId: m.id, lessonId: l.id }))
  );
  const currentIdx = allLessons.findIndex(l => l.lessonId === currentLessonId);
  if (currentIdx === -1 || currentIdx === allLessons.length - 1) return null;

  const next = allLessons[currentIdx + 1];
  return getLessonById(next.lessonId);
}

/**
 * Get total lesson count
 */
export function getTotalLessonCount() {
  return LEARNING_MODULES.reduce((sum, m) => sum + m.lessons.length, 0);
}

/**
 * Estimate audio duration from script lines
 * ~150 words per minute at 1.0x speed, pauses add ~2s each
 */
export function estimateAudioDuration(lines) {
  const wordCount = lines.filter(l => l !== '...').join(' ').split(/\s+/).length;
  const pauseCount = lines.filter(l => l === '...').length;
  const speakingSeconds = (wordCount / 150) * 60;
  const pauseSeconds = pauseCount * 2;
  return Math.ceil((speakingSeconds + pauseSeconds) / 60); // in minutes
}
