-- Health monitoring tables for scheduled health checks
-- Migration: 20260406_health_monitoring.sql

-- ── Health check history ────────────────────────────────────────────
-- Stores the result of every scheduled health check run.

CREATE TABLE IF NOT EXISTS public.health_check_history (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  checked_at timestamptz DEFAULT now(),
  overall_status text NOT NULL,
  database_ok boolean,
  anthropic_ok boolean,
  tts_ok boolean,
  stripe_ok boolean,
  total_users int,
  active_24h int,
  sessions_today int,
  errors_24h int,
  details jsonb
);

ALTER TABLE public.health_check_history ENABLE ROW LEVEL SECURITY;

-- Only service role can insert/read (no user-facing access)
CREATE POLICY "Service role only" ON public.health_check_history
  FOR ALL USING (auth.role() = 'service_role');

-- Index for time-range queries (anomaly detection lookback)
CREATE INDEX IF NOT EXISTS idx_health_check_history_checked_at
  ON public.health_check_history (checked_at DESC);

-- Auto-prune: keep 30 days of history (runs every 15 min, old rows pile up)
-- A simple approach: delete rows older than 30 days on each insert via trigger.
CREATE OR REPLACE FUNCTION public.prune_health_check_history()
RETURNS trigger AS $$
BEGIN
  DELETE FROM public.health_check_history
  WHERE checked_at < now() - interval '30 days';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_prune_health_check_history
  AFTER INSERT ON public.health_check_history
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.prune_health_check_history();


-- ── System notifications ────────────────────────────────────────────
-- Alerts and warnings generated by the scheduled health check.

CREATE TABLE IF NOT EXISTS public.system_notifications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  severity text NOT NULL CHECK (severity IN ('info', 'warning', 'alert', 'critical')),
  title text NOT NULL,
  message text,
  resolved boolean DEFAULT false,
  resolved_at timestamptz
);

ALTER TABLE public.system_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only" ON public.system_notifications
  FOR ALL USING (auth.role() = 'service_role');

-- Index for unresolved notifications (dashboard queries)
CREATE INDEX IF NOT EXISTS idx_system_notifications_unresolved
  ON public.system_notifications (created_at DESC)
  WHERE resolved = false;

-- Index for deduplication lookback
CREATE INDEX IF NOT EXISTS idx_system_notifications_title_created
  ON public.system_notifications (title, created_at DESC);
